# Generated by Django 4.1 on 2023-06-29 18:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('borough', models.CharField(max_length=13)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'maps"."zone',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='taxizone',
            name='borough',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
    ]
