# Generated by Django 4.1 on 2023-06-30 00:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zone_taxizone_borough'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puma',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'maps"."puma',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='TaxiZone',
        ),
    ]
