# Generated by Django 4.1 on 2023-06-29 23:02

from django.db import migrations
import json
from django.contrib.gis.geos import GEOSGeometry


class Migration(migrations.Migration):

    def taxi_zone_populate(apps, schema_editor):
        Zone = apps.get_model("main","Zone")
        if Zone.objects.count()==0:
            with open('../data-ingestions/nyc-taxi-zones.geojson', 'r') as fd:    
                data = json.load(fd)
                for feature in data['features']:
                    geom = GEOSGeometry(str(feature['geometry']))
                    geonameid = feature['properties']['objectid']
                    geoname = feature['properties']['zone']
                    geoborough = feature['properties']['borough']
                    zone = Zone(
                        id=geonameid,
                        geom=GEOSGeometry(geom),
                        name=geoname,
                        borough=geoborough)
                    zone.save()
        else:
            pass

    def puma_populate(apps, schema_editor):
        Puma = apps.get_model("main","Puma")
        if Puma.objects.count()==0:
            with open('../data-ingestions/nyc-pumas.geojson', 'r') as fd:    
                data = json.load(fd)
                for feature in data['features']:
                    geom = GEOSGeometry(str(feature['geometry']))
                    geonameid = feature['properties']['puma']
                    puma = Puma(
                        id=geonameid,
                        geom=GEOSGeometry(geom))
                    puma.save()
        else:
            pass

    dependencies = [
        ('main', '0003_puma_delete_taxizone'),
    ]

    operations = [
        migrations.RunPython(taxi_zone_populate),
        migrations.RunPython(puma_populate)
    ]
