# Generated by Django 4.1 on 2023-07-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_history_2023_04_30_23'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='current_impression',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
