# Generated by Django 4.1 on 2023-07-24 21:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_zone_current_impression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('small_cate', models.CharField(max_length=50)),
                ('big_cate', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'maps"."place',
                'managed': True,
            },
        ),
    ]
