# Generated by Django 4.1 on 2023-07-27 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
