# Generated by Django 4.1 on 2023-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_place_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='current_impression',
        ),
        migrations.AddField(
            model_name='zonedetail',
            name='borough',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='entertainment_and_recreation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='financial_services',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='food_and_beverage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='hospital',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='hotspots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='impression_history',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='impression_predict',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='parking_and_automotive_services',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='professional_services',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='real_estate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='retail_services',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='school',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='total_business',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='transportation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
