# Generated by Django 4.1 on 2023-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_place_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonedetail',
            name='borough',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='impression_history',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
