# Generated by Django 4.1 on 2023-07-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_zone_current_impression_zonedetail_borough_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonedetail',
            name='year_month',
        ),
        migrations.AddField(
            model_name='zonedetail',
            name='month',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
