# Generated by Django 4.1 on 2023-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_zonedetail_year_month_zonedetail_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='puma',
            name='females_15_24',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_25_34',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_35_44',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_45_54',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_55_64',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_5_14',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_65_74',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_75_84',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_85',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='females_under_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='main_demographic',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_15_24',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_25_34',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_35_44',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_45_54',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_55_64',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_5_14',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_65_74',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_75_84',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_85',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='males_under_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='puma',
            name='median_income',
            field=models.IntegerField(null=True),
        ),
    ]
