# Generated by Django 4.1 on 2023-07-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_zonepuma_intersect'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonepuma',
            unique_together={('zone', 'puma')},
        ),
    ]
