# Generated by Django 4.1 on 2023-07-29 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_zonepuma_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonedetail',
            name='place_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zonedetail',
            name='prediction_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='zonedetail',
            name='holiday',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
