# Generated by Django 4.1 on 2023-07-29 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_intersection_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonepuma',
            name='area',
        ),
        migrations.AlterField(
            model_name='zonepuma',
            name='puma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='puma_zone', to='main.puma'),
        ),
        migrations.AlterField(
            model_name='zonepuma',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='zone_puma', to='main.zone'),
        ),
    ]
