# Generated by Django 4.1 on 2023-07-18 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_zone_puma_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('zone_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('impression_history', models.PositiveIntegerField(default=0)),
                ('impression_predict', models.PositiveIntegerField(default=0)),
                ('year_month', models.CharField(max_length=7)),
                ('week', models.CharField(max_length=1)),
                ('hour', models.CharField(max_length=2)),
                ('entertainment_and_recreation', models.FloatField(default=0)),
                ('financial_services', models.FloatField(default=0)),
                ('food_and_beverage', models.FloatField(default=0)),
                ('parking_and_automotive_services', models.FloatField(default=0)),
                ('professional_services', models.FloatField(default=0)),
                ('real_estate', models.FloatField(default=0)),
                ('retail_services', models.FloatField(default=0)),
                ('transportation', models.FloatField(default=0)),
                ('hospital', models.FloatField(default=0)),
                ('hotspots', models.FloatField(default=0)),
                ('school', models.FloatField(default=0)),
                ('total_business', models.FloatField(default=0)),
                ('holiday', models.CharField(max_length=50)),
                ('taxi_zone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.zone')),
            ],
            options={
                'db_table': 'public"."impression',
                'managed': True,
                'unique_together': {('taxi_zone', 'datetime')},
            },
        ),
    ]
