# Generated by Django 4.1 on 2023-07-18 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_zone_puma_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('zone_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('year_month', models.CharField(max_length=7)),
                ('week', models.CharField(max_length=1)),
                ('hour', models.CharField(max_length=2)),
                ('holiday', models.CharField(max_length=50)),
                ('taxi_zone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.zone')),
            ],
            options={
                'db_table': 'public"."impression',
                'managed': True,
                'unique_together': {('taxi_zone', 'datetime')},
            },
        ),
    ]
