# Generated by Django 4.1 on 2023-07-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_zone_puma_populate'),
        ('impression', '0003_history_2023_04_30_22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='taxi_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='impression_in_zone', to='main.zone'),
        ),
    ]
