# Generated by Django 4.1 on 2023-07-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_date_joined_appuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
